# Generated by Django 2.1.1 on 2020-03-27 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64)),
                ('price', models.IntegerField()),
                ('faq_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiler.faq')),
            ],
        ),
        migrations.CreateModel(
            name='service_provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='service_receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_code', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='service_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('link', models.CharField(blank=True, max_length=64)),
                ('provider_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiler.service_provider')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_receiver_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiler.service_receiver'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_title_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiler.service_title'),
        ),
    ]
