# Generated by Django 2.1.1 on 2020-03-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='login',
        ),
    ]
